#!/bin/bash


TITLE=""
DURATION=""
EVENTSTART=""
EVENTEND=""

USER_HOME="$HOME"

DIR="$USER_HOME/.calendar"

if [ ! -d $DIR ]; then
{
	mkdir $DIR
	echo "dir made"
	echo $DIR
}
fi
function error_exit
{
	echo "$1" 1>&2
	exit 1
}

if [ "$1" == "create" ]; then
{

	if [ "$2" != "" ]; then
	{
	
			EVENTSTART=$(date --date="$2" "+%s")
			#echo $EVENTSTART
	}
	else
	{
		error_exit "Please Provide Date"	
	}
	fi

	if  [ "$3" != "" ]; then
	{
		DURATION=$3
		SECDURATION=$(($3*60))
		EVENTEND=$(($EVENTSTART+$SECDURATION ))
		#echo $EVENTEND		
	}
	else
	{
		error_exit "Please provide duration"	
	}
	fi	

	if [ "$4" != "" ]; then
	{
		TITLE="$4"
		#echo $TITLE	
	}
	else
	{
		read -p "Enter title of the event > " TITLE
		if [ "$TITLE" == "" ]; then 
		{
			error_exit "Title is required. Please Provide Title"
		}
		fi	
	}
	fi
	
	read DESCRIPTION < /dev/stdin
	#echo $DESCRIPTION

#	if [ "$DESCRIPTION" == "" ]; then
#	{
#		read -p "Enter a Description(optional)> " DESCRIPTION
#		#echo $DESCRIPTION
#	}
#	fi

	if [ ! -f $DIR/$EVENTSTART ]; then
	{
		echo -e $DURATION >> $DIR/$EVENTSTART 
		echo -e $TITLE >> $DIR/$EVENTSTART
 		echo -e $DESCRIPTION >> $DIR/$EVENTSTART
	}
	else
	{
		error_exit "Event Already exists at that time"
	}
	fi 
}

elif [ $1 == "delete" ]; then
{
	if [ -f $DIR/$2 ]; then
	{
		rm $DIR/$2
		echo "delelted file "
	}	
	else
	{
		error_exit "file does not exist"
	}
	fi	
	
}

elif [ $1 == "show" ]; then
{
	if [ -f $DIR/$2 ]; then
	{
		STARTTIME=$(date -d @$2)
		DURAT=$(awk 'NR==1' $DIR/$2)
	#	SECDURAT=$(())
		NEWTITLE=$(awk 'NR==2' $DIR/$2)
		NEWDESC=$(awk 'NR>=3' $DIR/$2)
		ENDTIMEEPOCH=$((($DURAT*60)+$2))
		ENDTIME=$(date -d @$ENDTIMEEPOCH)
		
	#	echo $ENDTIMEEPOCH
	#	echo "$2"
		if [ ! $3 ]; then
		{
			echo $STARTTIME to $ENDTIME
			echo $NEWTITLE
			echo $NEWDESC 
		}
		elif [ $3 == "title" ]; then
		{
			echo $NEWTITLE 
		}	
		elif [ $3 == "time" ]; then
		{
			echo $STARTTIME to $ENDTIME
		}
		elif [ $3 == "description" ]; then
		{
			echo $NEWDESC
		}
		else	
		{
			error_exit "Please provide correct option to display"
		}
		fi
	}
	else
	{
		error_exit "the file does not exist"
	}
	fi
}		
elif [ $1 == "link" ]; then
{
	LINKROOT="/home/$2"
    	if [ ! -d $LINKROOT ]; then
	{
		error_exit "the specified user does not exist"
	}
	else
	{	
		FILEROOT=$LINKROOT/.calendar/$3
		echo $FILEROOT
		if [ ! -f $FILEROOT ];then
		{
	 		 error_exit "specified event does not exist"
					
		}
		else
		{
			 ln -s $FILEROOT $DIR
                        echo "event linked"
		}
		fi		
	}
	fi		
}
else
{
	error_exit "option not found. use only create option"	
}

fi


