#!/usr/bin/awk

#1
BEGIN {FS = "|" ;
	SUM =0}
{SUM+=$5;}
END {print SUM}

#2
BEGIN{FS = "|" ;
	MAX =0;
	VALUE =0}
{if(MAX < $5)
{
	MAX = $5;
	VALUE = $3
}}
END{print VALUE}

#3
BEGIN{FS = "|";}
	
{
	TEMPVAL = int(($3)/10);
	ab[TEMPVAL]++; 
	#int TEMPVAL
#	print ab[TEMPVAL]
	

}

END {
	for (k in ab)
	{
#	print k;
#	print "a[K] "
#	print ab[k];
		if(MAXYEAR<ab[k])
		{
			MAXYEAR = ab[k];
			DECADE = k*10;
		}
	}
print DECADE
	 }
#4
BEGIN{FS = "|" ;
	ABOVEVAL =0;
	ABOVECOUNT =0;
	AVGABOVE=0;
	BELOWVAL=0;
	BELOWCOUNT=0;
	AVGBELOW =0;
	}

{
	RATING = $4
	VOTESRATE = $5;
	if (RATING > 8.5)
	{
		ABOVEVAL += VOTESRATE;
		ABOVECOUNT +=1
	}
	if (RATING < 8.5)
	{
		BELOWVAL += VOTESRATE;
		BELOWCOUNT +=1
	}

}
END{
	AVGABOVE = ABOVEVAL/ABOVECOUNT;
	AVGBELOW = BELOWVAL/BELOWCOUNT;
	printf("%f %f\n" ,AVGABOVE, AVGBELOW)
	 }	

#5

BEGIN {FS = "|" ;
       NBWORDS =0;
	AVGWORDS=0
}
{

NBWORDS += split($2,a," ")
	  
}

END{AVGWORDS = NBWORDS/FNR;
	printf ("%f\n" ,AVGWORDS)}

#6 

BEGIN {FS ="|"}

{
	split($2,newWord," ");
	for(k in newWord)
	{
		if (newWord[k] !~ "The") 
{	
		if (newWord[k] !~ "the")
{
		 if (newWord[k] !~ "of")
{
		wordCount[newWord[k]]++;
		#print "this is the new word";
		#print newWord[k];
}}}
	}
}

END{
	for(word in wordCount)
	{
#		print "this is the word";
#		print word;
		
			if(maxWordCount < wordCount[word])
			{
				maxWordCount = wordCount[word];
				finalWord = word;
			}
		
	}
print finalWord;
	}

#7
BEGIN {FS = "|";
	MAXWORDS=0;
	MINWORDS=9999;
}

{

WORDS = length($2);

if(MAXWORDS < WORDS)
{
	MAXWORDS =WORDS;
	MAXTITLE = $2;
			
}
if(MINWORDS>WORDS)
{
	MINWORDS =WORDS	
	MINTITLE = $2;

}
}
END {
	print MAXTITLE;
	
print MINTITLE 

}

